/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApplyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'apeworkflow-apply-change',
    description: 'Keep the ApeWorkflow apply shell and route task execution through methodology skills.',
    instructions: `Keep the ApeWorkflow apply shell and route task execution through methodology skills.

**Input**: Optionally specify a change name. If omitted, check if it can be inferred from conversation context. If vague or ambiguous you MUST prompt for available changes.

**Steps**

1. **Select the change**

   If a name is provided, use it. Otherwise:
   - Infer from conversation context if the user mentioned a change
   - Auto-select if only one active change exists
   - If ambiguous, run \`apeworkflow list --json\` to get available changes and use the **AskUserQuestion tool** to let the user select

   Always announce: "Using change: <name>" and how to override (e.g., \`/ape:apply <other>\`).

   **Config-aware selection:** Read \`apeworkflow/config.yaml\` for \`strictness.selectionPolicy\`:
   - \`auto-if-single\`: auto-select if only one active change exists (default)
   - \`always-prompt\`: always prompt the user
   - If not set, use \`auto-if-single\` as default behavior

   **Rich change display:** When prompting the user to select a change, include more context than just the schema name:
   - Run \`apeworkflow status --change "<name>" --json\` for each candidate change
   - Show: change name, schema, artifact completion count (e.g., "3/5"), whether \`plans\` artifact is done (needed for apply), and a brief description if available in the proposal.md
   - Prioritize or mark changes where \`plans\` is complete (they're ready to apply)
   - Flag changes where \`plans\` is incomplete (the user will need to generate plans first)
   - Example prompt:
     \`\`\`
     Which change to implement?

     1. add-login (spec-driven) — 5/5 artifacts, plans ✓ — "Add OAuth login"
     2. fix-header (spec-driven) — 2/5 artifacts, plans ✗ — "Fix header alignment"
     3. refactor-db (spec-driven) — 4/5 artifacts, plans ✓ — "Migrate to PostgreSQL"

     Tip: Only changes with plans ✓ are ready to implement. Others need plans first.
     \`\`\`

2. **Check status to understand the shell context**
   \`\`\`bash
   apeworkflow status --change "<name>" --json
   \`\`\`
   Parse the JSON to understand:
   - \`schemaName\`: The workflow being used (e.g., "spec-driven")
   - \`planningHome\`, \`changeRoot\`, and \`actionContext\`: planning scope and edit constraints
   - Which artifact contains the implementation plan and detailed plan file(s) (typically the files under \`plans/\`; check status for others)

3. **Get apply instructions and load the task list**

   \`\`\`bash
   apeworkflow instructions apply --change "<name>" --json
   \`\`\`

   This returns:
   - \`contextFiles\`: artifact ID -> array of concrete file paths (varies by schema - could be proposal/specs/design/tasks or spec/tests/implementation/docs)
   - Progress (total, complete, remaining)
   - Task list with status
   - Dynamic instruction based on current state

   **Handle states:**
   - If \`state: "blocked"\` (missing artifacts): show message, suggest using apeworkflow-continue-change
   - If \`state: "all_done"\`: congratulate, suggest archive
   - Otherwise: proceed to implementation

   **Workspace guard:** If status JSON reports \`actionContext.mode: "workspace-planning"\`, call \`resolveEditScope()\` to determine the edit scope. If mode is \`full\`, proceed. If mode is \`partial\`, present the available edit roots from the scope and ask the user to select an area. If mode is \`none\`, explain "No editable roots are available in this workspace. Suggested steps: 1) Use /ape:explore to analyze the workspace, 2) Create a sub-change targeting a specific sub-directory, 3) Or use /ape:propose with a specific affected area." Do NOT hard-STOP -- provide actionable next steps.

4. **Read context files**

   Read every file path listed under \`contextFiles\` from the apply instructions output.
   The files depend on the schema being used:
   - **spec-driven**: proposal, specs, design, and the detailed plan file(s) under \`plans/\`
   - Other schemas: follow the contextFiles from CLI output

   The detailed plan file(s) under \`plans/\` are the implementation source of truth.

   **Config-aware plan loading:** Read \`plan.granularity\` from config:
   - \`fine\`: load all artifacts entirely
   - \`medium\`: load proposal + relevant specs (default)
   - \`coarse\`: load task outline + proposal summary only
   - If not set, use \`medium\` as default

5. **Dispatch by task type**

   For each pending task, use the task type to choose the methodology Skill chain, then let that Skill chain do the concrete implementation work.

   **Task type routing algorithm:**
   a. Read the \`taskTypeRouting\` object from the \`apeworkflow instructions apply --change "<name>" --json\` output. It has shape: \`\`{ default: string[], taskTypes: { [typeName]: string[] } }\`\`
   b. For each task, extract its \`type\` field (set during writing-plans). If the task has no \`type\` field (value is \`undefined\`), use the \`default\` skill chain.
   c. If the task has a \`type\` field, look it up in \`taskTypeRouting.taskTypes[typeName]\`. If found, use that chain. If the type key doesn't exist in the routing table, fall back to \`default\`.
   d. Execute each skill in the matched chain sequentially.

   **Example:**
   - Task has \`type: "bugfix"\` — Look up \`taskTypeRouting.taskTypes["bugfix"]\` → \`[systematic-debugging, test-driven-development, executing-plans]\` → Execute in that order
   - Task has \`type: undefined\` → Use \`taskTypeRouting.default\` → \`[executing-plans, test-driven-development, subagent-driven-development]\`

   **Shell rule**: this command only owns selection, loading, routing, progress tracking, and pause/completion output. It does not describe or perform the detailed development steps itself.

6. **Show current progress**

   Display:
   - Schema being used
   - Progress: "N/M tasks complete"
   - Remaining tasks overview
   - Dynamic instruction from CLI

7. **On completion or pause, show status**

   Display:
   - Tasks completed this session
   - Overall progress: "N/M tasks complete"
   - If all done: suggest archive
   - If paused: explain why and wait for guidance

**Output During Implementation**

\`\`\`
## Implementing: <change-name> (schema: <schema-name>)

Working on task 3/7: <task description>
[...implementation happening...]
✓ Task complete

Working on task 4/7: <task description>
[...implementation happening...]
✓ Task complete
\`\`\`

**Output On Completion**

\`\`\`
## Implementation Complete

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 7/7 tasks complete ✓

### Completed This Session
- [x] Task 1
- [x] Task 2
...

All tasks complete! Ready to archive this change.
\`\`\`

**Output On Pause (Issue Encountered)**

\`\`\`
## Implementation Paused

**Change:** <change-name>
**Schema:** <schema-name>
**Progress:** 4/7 tasks complete

### Issue Encountered
<description of the issue>

**Options:**
1. <option 1>
2. <option 2>
3. Other approach

What would you like to do?
\`\`\`

**Guardrails**
- Keep going through tasks until done or blocked
- Always read context files before starting (from the apply instructions output)
- If task is ambiguous, pause and ask before implementing
- If implementation reveals issues, pause and suggest artifact updates
- Keep code changes minimal and scoped to each task
- Update task checkbox immediately after completing each task
- Pause on errors, blockers, or unclear requirements - don't guess
- Use contextFiles from CLI output, don't assume specific file names

**Fluid Workflow Integration**

This skill supports the "actions on a change" model:

- **Can be invoked anytime**: Before all artifacts are done (if tasks exist), after partial implementation, interleaved with other actions
- **Allows artifact updates**: If implementation reveals design issues, suggest updating artifacts - not phase-locked, work fluidly`,
    license: 'MIT',
    compatibility: 'Requires apeworkflow CLI.',
    metadata: { author: 'apeworkflow', version: '1.0' },
  };
}

export function getApeApplyCommandTemplate(): CommandTemplate {
  return {
    name: 'APE: Apply',
    description: 'Keep the ApeWorkflow apply shell and route task execution through methodology skills (Experimental)',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: getApplyChangeSkillTemplate().instructions,
  };
}
