/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getApeProposeSkillTemplate(): SkillTemplate {
  return {
    name: 'apeworkflow-propose',
    description: 'Propose a new change with core artifacts generated first, then refine them through brainstorming before writing the implementation plan.',
    instructions: `Propose a new change - create the change, generate the core artifacts, then refine them through brainstorming.

I'll create a change with artifacts first:
- proposal.md (what & why)
- design.md (how)
- tasks.md (task outline for plan generation, outline only)

After those artifacts are in place, I'll run brainstorming to refine requirements, patch the artifacts, and then hand off to writing-plans. When ready to implement, run /ape:apply.

---

**Input**: The user's request should include a change name (kebab-case) OR a description of what they want to build.

**Steps**

1. **If no clear input provided, ask what they want to build**

   Use the **AskUserQuestion tool** (open-ended, no preset options) to ask:
   > "What change do you want to work on? Describe what you want to build or fix."

   From their description, derive a kebab-case name (e.g., "add user authentication" → \`add-user-auth\`).

   **IMPORTANT**: Do NOT proceed without understanding what the user wants to build.

2. **Create the change directory**
   \`\`\`bash
   apeworkflow new change "<name>"
   \`\`\`
   This creates a scaffolded change in the planning home resolved by the CLI with \`.apeworkflow.yaml\`.

3. **Get the artifact build order**
   \`\`\`bash
   apeworkflow status --change "<name>" --json
   \`\`\`
   Parse the JSON to get:
   - \`applyRequires\`: array of artifact IDs needed before implementation (for this schema it is \`plans\`)
   - \`artifacts\`: list of all artifacts with their status and dependencies
   - \`planningHome\`, \`changeRoot\`, \`artifactPaths\`, and \`actionContext\`: path and scope context. Use these instead of assuming repo-local paths.

4. **Create artifacts in sequence until apply-ready**

   Use the **TodoWrite tool** to track progress through the artifacts.

   Loop through artifacts in dependency order (artifacts with no pending dependencies first):

   a. **For each artifact that is \`ready\` (dependencies satisfied)**:
      - Get instructions:
        \`\`\`bash
        apeworkflow instructions <artifact-id> --change "<name>" --json
        \`\`\`
      - The instructions JSON includes:
        - \`context\`: Project background (constraints for you - do NOT include in output)
        - \`rules\`: Artifact-specific rules (constraints for you - do NOT include in output)
        - \`template\`: The structure to use for your output file
        - \`instruction\`: Schema-specific guidance for this artifact type
        - \`resolvedOutputPath\`: Resolved path or pattern to write the artifact
        - \`dependencies\`: Completed artifacts to read for context
      - Read any completed dependency files for context
      - Create the artifact file using \`template\` as the structure and write it to \`resolvedOutputPath\`
      - Apply \`context\` and \`rules\` as constraints - but do NOT copy them into the file
      - Show brief progress: "Created <artifact-id>"

   b. **Continue until all \`applyRequires\` artifacts are complete**
      - After creating each artifact, re-run \`apeworkflow status --change "<name>" --json\`
      - Check if every artifact ID in \`applyRequires\` has \`status: "done"\` in the artifacts array
      - Stop when all \`applyRequires\` artifacts are done

   c. **If an artifact requires user input** (unclear context):
      - Use **AskUserQuestion tool** to clarify
      - Then continue with creation

   d. **Run brainstorming before implementation**
      - Re-read \`proposal.md\`, \`design.md\`, and \`tasks.md\` (the outline only)
      - Use \`brainstorming\` to fill any remaining requirement gaps, update the artifacts in place, and reconcile the three files
      - Hand off to \`writing-plans\` to create the detailed implementation plan file(s) under \`plans/\`

5. **Show final status**
   \`\`\`bash
   apeworkflow status --change "<name>"
   \`\`\`

**Output**

After completing all artifacts, summarize:
- Change name and location
- List of artifacts created with brief descriptions
- What's ready: "All artifacts created! Ready for implementation."
- Prompt: "Run \`/ape:apply\` or ask me to implement to start working on the tasks."

**Artifact Creation Guidelines**

- Follow the \`instruction\` field from \`apeworkflow instructions\` for each artifact type
- The schema defines what each artifact should contain - follow it
- Read dependency artifacts for context before creating new ones
- Use \`template\` as the structure for your output file - fill in its sections
- **IMPORTANT**: \`context\` and \`rules\` are constraints for YOU, not content for the file
  - Do NOT copy \`<context>\`, \`<rules>\`, \`<project_context>\` blocks into the artifact
  - These guide what you write, but should never appear in the output

**Guardrails**
- Create ALL artifacts needed for implementation (as defined by schema's \`apply.requires\`)
- Always read dependency artifacts before creating a new one
- If context is critically unclear, ask the user - but prefer making reasonable decisions to keep momentum
- If a change with that name already exists, ask if user wants to continue it or create a new one
- Verify each artifact file exists after writing before proceeding to next`,
    license: 'MIT',
    compatibility: 'Requires apeworkflow CLI.',
    metadata: { author: 'apeworkflow', version: '1.0' },
  };
}

export function getApeProposeCommandTemplate(): CommandTemplate {
  return {
    name: 'APE: Propose',
    description: 'Propose a new change - create it, refine the core artifacts, and then write the implementation plan',
    category: 'Workflow',
    tags: ['workflow', 'artifacts', 'experimental'],
    content: getApeProposeSkillTemplate().instructions,
  };
}
