/**
 * Skill Template Workflow Modules
 *
 * This file is generated by splitting the legacy monolithic
 * templates file into workflow-focused modules.
 */
import type { SkillTemplate, CommandTemplate } from '../types.js';

export function getVerifyChangeSkillTemplate(): SkillTemplate {
  return {
    name: 'apeworkflow-verify-change',
    description: 'Verify implementation matches change artifacts. Use when the user wants to validate that implementation is complete, correct, and coherent before archiving.',
    instructions: `1. Select a change (or let the user choose)
2. Check status: \`apeworkflow status --change "<name>" --json\`
   If status reports \`actionContext.mode: "workspace-planning"\`, STOP -- full workspace implementation verification is not supported.
3. Perform three-dimension verification: Completeness, Correctness, Coherence
4. Display report: scorecard + issues by priority (CRITICAL/WARNING/SUGGESTION)`,
    license: 'MIT',
    compatibility: 'Requires apeworkflow CLI.',
    metadata: { author: 'apeworkflow', version: '1.0' },
  };
}

export function getApeVerifyCommandTemplate(): CommandTemplate {
  return {
    name: 'APE: Verify',
    description: 'Verify implementation matches change artifacts before archiving',
    category: 'Workflow',
    tags: ['workflow', 'verify', 'experimental'],
    content: `---
name: "APE: Verify"
description: "Verify implementation matches change artifacts"
category: Workflow
tags: [workflow, verify]
---

1. Select a change (or let the user choose)
2. Check status: \`apeworkflow status --change "<name>" --json\`
3. Delegate to apeworkflow-verification skill for three-dimension verification
4. Display report: scorecard + issues by priority (CRITICAL/WARNING/SUGGESTION)
`
  };
}
